version: '3.8'
services:
  minecraft:
    container_name: minecraft
    image: itzg/minecraft-server:${IMAGE_TAG:-latest}
    ports:
      - 25565:25565
      - 25565:25565/udp
    volumes:
      - ./data:/data
    env_file:
      - .env
    environment:
      - EULA=true
    restart: on-failure
